import { Toaster } from '@/components/ui/toaster';

import { Inter } from 'next/font/google';
import './globals.css';
import { NextAuthProvider } from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider>
          {children}
          {modal}
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
